# Generated by Django 3.2 on 2021-06-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='news/images')),
                ('document', models.FileField(upload_to='news/files')),
            ],
        ),
    ]
