# Generated by Django 3.2 on 2021-06-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_filenews'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenews',
            name='images',
            field=models.ImageField(blank=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='filenews',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='news/files'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
