# Generated by Django 3.2 on 2021-06-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210622_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='news/files'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/images'),
        ),
    ]
