# Generated by Django 3.2 on 2021-06-23 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
