# Generated by Django 3.2 on 2021-06-28 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenews',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filesNews', to='news.news'),
        ),
    ]
