# Generated by Django 3.2 on 2021-06-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
