# Generated by Django 3.2 on 2021-04-28 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='crated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 21, 50, 15, 788798, tzinfo=utc)),
        ),
    ]
