# Generated by Django 3.2 on 2021-04-28 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_alter_cours_crated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='crated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
