# Generated by Django 3.2 on 2021-04-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_alter_cours_crated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(default=1, upload_to='cours'),
            preserve_default=False,
        ),
    ]
